main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Story1, name='Story1'),
    path('Story3_aboutme', views.Story3_aboutme, name='aboutme'),
    path('Story3_contact', views.Story3_contact, name='contact'),
    path('Story3_eduskill', views.Story3_eduskill, name='eduskill'),
    path('home', views.home, name='home'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path
from webs8.views import home, data

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story7/', include('webs7.urls')),
    path('story8/', include('webs8.urls')),
    path('data', data),
    path('story9/', include('webs9.urls')),
]

webs7/urls.py
from django.urls import path
from . import views

app_name = 'webs7'

urlpatterns = [
    path('', views.story7_home, name="s7h"),
]

webs8/urls.py
from django.urls import path
from . import views

app_name = 'webs8'

urlpatterns = [
    path('', views.home, name="s8h"),
    path('data/', views.data, name="s8gd"),
]

webs9/urls.py
from . import views
from django.urls import path

app_name = 'webs9'

urlpatterns = [
    path('', views.story9, name ='s9'),
    path('signup', views.signup, name='s9s'),
    path('login', views.login, name='s9li'),
    path('logout', views.logout, name='s9lo'),
]

main/models.py
from django.db import models

# Create your models here.

webs7/models.py
from django.db import models

# Create your models here.

webs8/models.py
from django.db import models

# Create your models here.

webs9/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render




def Story1(request):
    return render(request, 'main/Story1.html')

def Story3_aboutme(request):
    return render(request, 'main/Story3_aboutme.html')

def Story3_contact(request):
    return render(request, 'main/Story3_contact.html')

def Story3_eduskill(request):
    return render(request, 'main/Story3_eduskill.html')

def home(request):
    return render(request, 'main/home.html')

webs7/views.py
from django.shortcuts import render

# Create your views here.
def story7_home(request):
    return render(request, "story7_home.html")

webs8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json
# Create your views here.

def home(request):
    response = {}
    return render(request, "story8_home.html", response)

def data(request):
    arg = request.GET['q']
    url_tujuan = "https://www.googleapis.com/books/v1/volumes?q=" + arg
    r = requests.get(url_tujuan)
    data = json.loads(r.content)
    return JsonResponse(data, safe=False)

webs9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login as dj_login
from django.contrib.auth import logout as django_logout
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.

def story9(request):
    return render(request, 'Story9.html')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
 
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            return redirect('webs9:s9li')
         
        else:
            return render(request,'Story9_signup.html',{'form':form})
     
    else:
        form = UserCreationForm()
        return render(request,'Story9_signup.html',{'form':form})

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
 
        if user is not None:
            dj_login(request,user)
            return redirect('/story9')
        else:
            form = AuthenticationForm()
            messages.error(request, 'Username atau password Anda salah')
            return render(request,'Story9_login.html',{'form':form})
     
    else:
        form = AuthenticationForm()
        return render(request, 'Story9_login.html', {'form':form})

def logout(request):
    django_logout(request)
    return  HttpResponseRedirect('/story9')

main/templates/main/Story1.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<style>
    html{background-color:rgb(68, 150, 182) ;}
    .Story1{background-color:rgb(68, 150, 182) ;}
</style>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color:rgb(68, 150, 182)">
    <a class="navbar-brand" href="#">BIODATA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'main:home' %}">Story 3</a>
      </div>
    </div>
</nav>
    <div class="Story1">
        <img src="https://scontent-xsp1-2.xx.fbcdn.net/v/t1.0-9/2023_114083358968846_8137644105767008273_n.jpg?_nc_cat=101&_nc_sid=09cbfe&_nc_eui2=AeHKpKQmiyLaoebc2WaWd1SMOZhs_gaJAwU5mGz-BokDBTJ_7Zznc1vyT7ps7k2GLHBpN7QxvMoS-ZP5IktUOvJN&_nc_ohc=-7IU7ZyDc1gAX-jjRS4&_nc_ht=scontent-xsp1-2.xx&oh=f7be915e5d77daab31cd675b16f003b3&oe=5F9179A1" alt="Foto saya" width="300" height="300">
        <br>
        <h2>Perkenalkan, nama saya Muhammad Daffa Yudhistira Dwipayana</h2>
        <p>NPM : 1906353441</p>
        <p>Umur : 19 tahun</p>
        <p>Angkatan : 2019</p>
        <p>Hobi : Bermain game dan membaca komik</p>
        <p>Tempat kuliah : Universitas Indonesia</p>
        <h3>Deskripsi diri</h3>
        <p>Jika saya harus mendeskripsikan diri saya, saya orangnya itu baik dan ramah terhadap orang lain.<br>
            Sifat buruk saya diantaranya adalah agak pemalas jika mengerjakan sesuatu yang sulit.<br>Namun,
            jika saya menemukan suatu hal yang saya suka dan bisa saya kerjakan,<br> saya akan bersungguh-sungguh 
            dalam mengerjakan hal tersebut.
        </p>   
        <h3>Riwayat Pendidikan</h3>
        <ol>
            <li>SDI PB Soedirman</li>
            <li>SMP Negeri 103 Jakarta</li>
            <li>SMA Negeri 98 Jakarta</li>
        </ol>
        <h3>Media Sosial</h3>
        <ul>
            <li>Line id : daffayudhis89</li>
            <li>Nomor Hp : 085772746486</li>
            <li>Alamat E-mail : daffayudhistira27@gmail.com</li>
        </ul>
    </div>
{% endblock content %}
</html>

main/templates/main/Story3_aboutme.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html>
    {% block meta %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% endblock meta %}

    {% block content %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Fafdax</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'main:home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'main:eduskill' %}">Educations and skills</a>
                <a class="nav-item nav-link" href="{% url 'main:contact' %}">Contacts</a>
                <a class="nav-item nav-link" href="{% url 'main:Story1' %}">Story 1</a>
              </div>
            </div>
        </nav>
        <img src="{% static 'img/Foto profil.jpg' %}" alt="My photo" width="400" height="350" style="vertical-align:middle;margin:40px 480px">
        <div class="bio">
            <p>Nama lengkap: Muhammad Daffa Yudhistira Dwipayana</p>
            <p>NPM : 1906353441</p>
            <p>Umur : 19 tahun</p>
            <p>Angkatan : 2019</p>
            <p>Hobi : Bermain game dan membaca komik</p>
            <p>Tempat kuliah : Universitas Indonesia</p>
        </div>
        <br>
        <div class="desc">
            <h3>Deskripsi diri</h3>
            <p>Jika saya harus mendeskripsikan diri saya, saya orangnya itu baik dan ramah terhadap orang lain.<br>
            Sifat buruk saya diantaranya adalah agak pemalas jika mengerjakan sesuatu yang sulit.<br>Namun,
            jika saya menemukan suatu hal yang saya suka dan bisa saya kerjakan,<br> saya akan bersungguh-sungguh 
            dalam mengerjakan hal tersebut.
            </p>   
        </div>
    {% endblock content %}
</html>

main/templates/main/Story3_contact.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html>
    {% block meta %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% endblock meta %}

    {% block content %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Fafdax</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'main:aboutme' %}">About me</a>
                <a class="nav-item nav-link" href="{% url 'main:eduskill' %}">Educations and skills</a>
                <a class="nav-item nav-link" href="{% url 'main:home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'main:Story1' %}">Story 1</a>
              </div>
            </div>
        </nav>
        
        <div class="contacts">
            <h2>You can contact me here:</h2>
            <br>
            <img src="{% static 'img/line logo.png' %}" class="rounded mx-auto d-block" alt="Line" width="50" height="50">
            <h3>Line: daffayudhis89</h3>
            <br>
            <img src="{% static 'img/email logo.jpg' %}" class="rounded mx-auto d-block" alt="E-mail" width="50" height="50">
            <h3>Email: daffayudhistira27@gmail.com</h3>
            <br>
            <img src="{% static 'img/phone logo.png' %}" class="rounded mx-auto d-block" alt="Phone" width="50" height="50">
            <h3>Phone: 085772746486</h3>
        </div>
    {% endblock content %}
</html>

main/templates/main/Story3_eduskill.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html>
    {% block meta %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> 
        <style>
          h2{
            text-align: center;
            color: white;
          }
        </style>   
    {% endblock meta %}
     
    {% block content %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Fafdax</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'main:aboutme' %}">About me</a>
                <a class="nav-item nav-link" href="{% url 'main:home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'main:contact' %}">Contacts</a>
                <a class="nav-item nav-link" href="{% url 'main:Story1' %}">Story 1</a>
              </div>
            </div>
        </nav>
        <br>
        <h2>Here's some brief history about my educations:</h2>
        <div class="education">
            <p><b>SDI PB Soedirman</b></p> 
            <img src="{% static 'img/SDI PB Soedirman.jpg' %}" class="rounded mx-auto d-block" alt="SDI PB Soedirman" width="150" height="150">
            <br>
            <p><b>SMP Negeri 103 Jakarta</b></p> 
            <img src="{% static 'img/SMPN 103.png' %}" class="rounded mx-auto d-block" alt="SMP Negeri 103 Jakarta" width="150" height="150">
            <br>
            <p><b>SMA Negeri 98 Jakarta</b></p>
            <img src="{% static 'img/SMAN 98.jpg' %}" class="rounded mx-auto d-block" alt="SMA Negeri 98 Jakarta" width="150" height="150">
        </div>
        <br>
        <h2>And here's what I'm good at (currently)</h2>
        <div class="skills">
            <p><b>Python</b></p>
            <img src="{% static 'img/Python image.png' %}" class="rounded mx-auto d-block" alt="Python" width="150" height="150">
            <br>
            <p><b>Java</b></p>
            <img src="{% static 'img/Java image.png' %}" class="rounded mx-auto d-block" alt="Java" width="150" height="150">
            <br>
            <p><b>HTML</b></p>
            <img src="{% static 'img/HTML image.png' %}" class="rounded mx-auto d-block" alt="HTML" width="150" height="150">
        </div>
    {% endblock content %}
</html>

main/templates/main/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html>
    {% block meta %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <style>
            div{
                text-align: center;
                font-size: 24;
                color: white;
            }
            h1{
                color: white;
                text-align: center;
            }
        </style>
    {% endblock meta %}

    {% block content %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Fafdax</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'main:aboutme' %}">About me</a>
                <a class="nav-item nav-link" href="{% url 'main:eduskill' %}">Educations and skills</a>
                <a class="nav-item nav-link" href="{% url 'main:contact' %}">Contacts</a>
                <a class="nav-item nav-link" href="{% url 'main:Story1' %}">Story 1</a>
              </div>
            </div>
          </nav>
    <img src="{% static 'img/Foto profil.jpg' %}" alt="My photo" width="400" height="350" style="vertical-align:middle;margin:40px 500px">
    <h1><i>Hello, my name is Daffa</i></h1>
    <div><b>I'm a newbie programmer and web developer</b><br><b>Nice to meet you!</b></div>
    {% endblock content %}
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
</body>
  {% block content %}
  {% endblock content %}
</html>

webs7/templates/story7_home.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"></script>
        <style>
            .container {
                width: 500px;
                height: auto;
                margin: 0 auto;
            }

            .item {
                display: block;
                width: inherit;
                
                line-height: 40px;
                background: #555;
                border: 1px solid #000;
                cursor: pointer;
                color: #fff;
            }

            .item-data {
                display: none; 
                width: inherit;
                height: auto;
                border: 1px solid #ccc;
            }

            .active {
                background: #eee;
                color: #000;
            }

            .item-data div{
                margin: 30px;
            }

            input{
                background: red;
            }
        </style>
    <script>
        $(document).ready(function(e){
            $('.item').click(function (e){
                if($(this).next('.item-data').css('display') != 'block'){
                $('.active').slideUp('fast').removeClass('active');
                $(this).next('.item-data').addClass('active').slideDown('slow');
                
                } else {
                $('.active').slideUp('fast').removeClass('active');
                }
            });
            
            $('.up-button').click(function(){
            $(this).parents('.item').insertBefore($(this).parents('.item').prev());
            });

            $('.down-button').click(function(){
            $(this).parents('.item').insertAfter($(this).parents('.item').next());
            });                                
        });
    </script>
    </head>

    <body class="bg-primary">
        <nav class="navbar navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Story 7</a>
        </nav>
        <div class="d-flex flex-md-row flex-column justify-content-between mt-4 mb-4">
            <div class='container'>
                <div class='item'>
                  <div>
                  Tentang Saya
                  <input type="button"value="^" class="up-button"/>  
                   <input type="button" value="v" class="down-button"/>
                  </div>
              
                </div>
                <div class='item-data'>
                  <div>Nama Saya Muhammad Daffa Yudhistira Dwipayana</div>
                </div>
                
              
                <div class='item'>
                      <div>
                        Hobi
                        <input type="button"value="^" class="up-button"/>  
                        <input type="button" value="v" class="down-button"/>
                      </div>
                    </div>
                  <div class='item-data'>
                    <div>Hobi saya main game dan membaca komik</div>
                </div>
              
                  
                  
                <div class='item'>
                    <div>
                      Prestasi
                      <input type="button"value="^" class="up-button"/>  
                      <input type="button" value="v" class="down-button"/>
                    </div>
                  </div>
                <div class='item-data'>
                  <div>Pernah mendapat nilai 100 pada UN IPA SD, dan juara 4 pada lomba sempoa</div>
              </div>
        </div>
        
    </body>

</html>

webs8/templates/story8_home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <style>
            table, th, td{
                border: 1px solid black;
            }
            #hasil{
                margin:2cm;
            }
            @media screen and (max-width: 1100px) {
                #hasil{
                   margin-right: 1cm;
                   margin-left: 1cm;
                }
            } 
        </style>
    </head>

    <body>
        <input id="key" placeholder="Cari buku">
        <table id="hasil" >
           
        </table>
        <script type="text/javascript">
            $('#key').keyup(function(){
                var isi = $('#key').val();
                var url_tujuan = "/data?q=" + isi;
                $.ajax({
                    url:url_tujuan,
                    success: function(result){
                        var obj = $("#hasil");
                        obj.empty();
                        for (i=0; i<result.items.length; i++){
                            var title = result.items[i].volumeInfo.title;
                            var gambar = result.items[i].volumeInfo.imageLinks.smallThumbnail;
                            obj.append('<tr><td>' + title + '</td><td><img src=' + gambar + '></td></tr>');
                        }
                    }
                });
            });
        </script>
    </body>
</html>

webs9/templates/Story9.html
<!DOCTYPE html>
<head>
    <title>Fafdax</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body style="background-color: rgb(161, 161, 228);">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Fafdax</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            {% if user.is_authenticated %}
                <a class="nav-link"><img src="https://peopleshub.org/wp-content/uploads/2018/04/person-icon-white.png" style="width: 30px; height: 30px; vertical-align:bottom; margin-top: -14px; color: white;">Hello, {{ user.get_username }}</a>
                <a class="nav-link" href="{% url 'webs9:s9lo' %}"><img src="https://icon-library.com/images/logout-icon-png/logout-icon-png-3.jpg" style="width: 30px; height: 30px; vertical-align:bottom; margin-top: -14px; color: white;">Logout</a>
            {% else %}
                <a class="nav-link"><img src="https://peopleshub.org/wp-content/uploads/2018/04/person-icon-white.png" style="width: 30px; height: 30px; vertical-align:bottom; margin-top: -14px; color: white;">Hello, Guest</a>
                <a class="nav-link" href="{% url 'webs9:s9li' %}"><img src="https://icon-library.com/images/11a7acda9d.png" style="width: 30px; height: 30px; vertical-align:bottom; margin-top: -14px; color: white;">Login</a>
            {% endif %}
          </div>
        </div>
      </nav>

    <div class="container" style="display: flex; align-items: center; justify-content: center; height: 400px;" >
        <div>
            {% if user.is_authenticated %}
                <h1>Selamat Datang, {{ user.get_username }} !</h1>
            {% else %}
                <h1>Selamat Datang, Guest !</h1>
            {% endif %}
        </div>
    </div>
</body>

webs9/templates/Story9_login.html
<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>

<body style="background-color: rgb(161, 161, 228);">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Fafdax</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    </nav>

        <form method='POST' style="padding: 100px 200px;">
            <h2>Log In</h2><br>
            {% csrf_token %}
            {{form.as_p}}
            <br><br>
            {% for message in messages %}
                {% if message.tags == 'error' %}
                    <div class="alert alert-danger" role="alert">{{ message }}</div>
                    <br><br>
                {% endif %}
            {% endfor %}
    
            <input style="background-color: rgb(17, 17, 61); color: white; margin-left: 0px; padding: 8px 10px; font-size: 16px;" type = "submit" value = "Log in">
            <br><br>
            <p>Belum punya akun ? <a class="btn btn-primary" href = "{% url 'webs9:s9s' %}"> Sign up dulu di sini</a></p><br>
        </form>

</body>

webs9/templates/Story9_signup.html
<title>Sign Up</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<body style="background-color: rgb(161, 161, 228);">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Fafdax</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <div class="signup">
        <form id="signup" method='POST' style="padding: 100px 200px;">
            <h2>Sign Up</h2><br>
            {% csrf_token %}
            {% for field in form %}
                <p>
                {{ field.label_tag }}<br>
                <p class="inputan">{{ field }}</p>
                {% for error in field.errors %}
                    <p style="color: rgb(179, 0, 0)">{{ error }}</p>
                {% endfor %}
                </p>
            {% endfor %}
            <br>
            <input style="background-color: rgb(17, 17, 61); color: white; margin-left: 0px; padding: 8px 10px; font-size: 16px;" type="submit" value = "Sign up">
            <br><br>
            <p>Sudah punya akun? <a class="btn btn-danger" href="{% url 'webs9:s9li' %}">Langsung log in di sini</a></p>
        </form>    
    </div>
</body>